### ISSUE TITLE
duplicate list of todos in view

### ISSUE THREAD

**Issue by marco-solare** [arvindr21/MEAN-Todo-App#5]
Hi, just another little comment:
in the file
`client/partials/todo.html`
there seems to be a couple of lines that have been duplicated for no obvious reason (to me).
I was wondering why I was getting two lists of todos after having cloned the app.
So I tried to track down the cause of this.
Turned out that in the above named file there where two `ng-repeat` sections with what seemed to me duplicated code.
After having deleted the second one and removing one last div that seemed to be duplicate, too  I ended up with a perfectly well-working version of your app :)

Didn't you experience this problem?
Best, Marco

**Comment by arvindr21** [comment]
My Bad. Fixed it : https://github.com/arvindr21/MEAN-Todo-App/commit/c3c8b8158f2b27d09ca6f866712aa7102edf23d8#diff-40de427ae075e4f5f9f5ac3a311e4b69. Thanks for pointing it out.

**Comment by marco-solare** [comment]
Nevermind, now it's a pretty perfect thing, thanks for providing this gulp / MEAN based tut & app, was excactly what I was searching for

**Comment by arvindr21** [comment]
:+1:
